from pathlib import Path


FRONTEND_INDEX = Path(__file__).resolve().parents[1] / "frontend" / "index.html"


def _frontend_source() -> str:
    return FRONTEND_INDEX.read_text(encoding="utf-8")


def _function_body(source: str, function_name: str) -> str:
    start = source.index(f"function {function_name}")
    next_function = source.find("\nfunction ", start + len(function_name))
    if next_function == -1:
        return source[start:]
    return source[start:next_function]


def test_standard_result_view_surfaces_uncertainty_above_the_fold():
    source = _frontend_source()

    assert "function buildUncertaintyWarnings" in source
    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in source
    assert "uncertainty-warning-card" in source
    assert "Verify before relying on this result" in source

    hero_pos = source.index('html += `<div class="result-hero">')
    warning_pos = source.index("uncertainty-warning-card")
    assert warning_pos < hero_pos


def test_report_view_uses_same_loud_uncertainty_rollup():
    source = _frontend_source()

    assert "const reportUncertaintyWarnings = buildUncertaintyWarnings(d);" in source
    assert "Report needs verification" in source
    assert "This warning is intentionally shown in report/print view" in source

    report_header_pos = source.index("PermitAssist Report v1.0")
    report_warning_pos = source.index("Report needs verification")
    first_field_pos = source.index("// The 18 fields — locked order")
    assert report_header_pos < report_warning_pos < first_field_pos


def test_copy_result_preserves_uncertainty_warning():
    source = _frontend_source()

    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in source
    assert "VERIFY BEFORE RELYING:" in source
    assert "Uncertainty / verification warnings" in source
    assert source.index("VERIFY BEFORE RELYING:") < source.index("Generated by PermitAssist")


def test_dallas_evidence_exposure_limits_are_visible_in_standard_report_and_copy_views():
    source = _frontend_source()

    required = [
        "Evidence-pack exposure limits",
        "Failed-closed evidence fields:",
        "fee_range",
        "inspections",
        "statutory/AHJ outer deadline only — not a local queue or plan-review estimate",
        "not a complete local specialty-trigger list",
        "Exact portal subcategory and filing path still need AHJ/portal verification before filing",
        "Failed-closed evidence fields:",
    ]
    for text in required:
        assert text in source

    standard_warning_pos = source.index("Evidence-pack exposure limits")
    hero_pos = source.index('html += `<div class="result-hero">')
    assert standard_warning_pos < hero_pos

    report_warning_pos = source.index("Report needs verification")
    missing_rollup_pos = source.index("failed closed: ${field}")
    assert report_warning_pos < missing_rollup_pos


def test_dallas_evidence_caveats_are_surface_scoped_to_copy_and_report():
    source = _frontend_source()
    copy_body = _function_body(source, "copyResult")
    report_body = _function_body(source, "renderResultAsReport")
    warning_builder_body = _function_body(source, "buildUncertaintyWarnings")

    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in copy_body
    assert "reportUncertaintyWarnings.map" in report_body
    assert "const reportUncertaintyWarnings = buildUncertaintyWarnings(d);" in report_body
    assert "buildEvidencePackCaveats(evidencePack)" in warning_builder_body
    assert "buildEvidencePackCaveats(evidencePack)" in warning_builder_body.split("qualityWarnings.slice", 1)[0]
    assert "slice(0, 14)" in warning_builder_body

    shared_builder_body = _function_body(source, "buildEvidencePackCaveats")
    required_surface_caveats = [
        "not a complete local specialty-trigger list",
        "Exact portal subcategory and filing path still need AHJ/portal verification before filing",
    ]

    for caveat in required_surface_caveats:
        assert caveat in shared_builder_body


def test_dallas_evidence_surfaces_use_one_shared_caveat_builder():
    source = _frontend_source()

    assert "function buildEvidencePackCaveats" in source
    assert _function_body(source, "renderResults").count("buildEvidencePackCaveats") >= 1
    assert _function_body(source, "buildUncertaintyWarnings").count("buildEvidencePackCaveats") >= 1
