from pathlib import Path


FRONTEND_INDEX = Path(__file__).resolve().parents[1] / "frontend" / "index.html"


def _frontend_source() -> str:
    return FRONTEND_INDEX.read_text(encoding="utf-8")


def _function_body(source: str, function_name: str) -> str:
    start = source.index(f"function {function_name}")
    next_function = source.find("\nfunction ", start + len(function_name))
    if next_function == -1:
        return source[start:]
    return source[start:next_function]


def test_standard_result_view_keeps_small_ahj_caveat_without_loud_uncertainty_card():
    source = _frontend_source()
    render_body = _function_body(source, "renderResults")

    assert "function buildUncertaintyWarnings" in source
    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in render_body
    assert "PermitAssist is guidance only" in render_body
    assert "Verify final permit type with the AHJ before quoting or starting work" in render_body
    assert "uncertainty-warning-card" not in render_body
    assert "Verify before relying on this result" not in render_body

    caveat_pos = render_body.index("PermitAssist is guidance only")
    hero_pos = render_body.index('html += `<div class="result-hero">')
    assert caveat_pos < hero_pos


def test_report_view_keeps_only_small_ahj_caveat_without_loud_uncertainty_rollup():
    source = _frontend_source()
    report_body = _function_body(source, "renderResultAsReport")

    assert "PermitAssist is guidance only" in report_body
    assert "Verify final permit type with the AHJ before quoting or starting work" in report_body
    assert "const reportUncertaintyWarnings = buildUncertaintyWarnings(d);" not in report_body
    assert "Report needs verification" not in source
    assert "This warning is intentionally shown in report/print view" not in source
    assert "reportUncertaintyWarnings.map" not in report_body

    report_header_pos = source.index("PermitAssist Report v1.0")
    small_warning_pos = source.index("PermitAssist is guidance only", report_header_pos)
    first_field_pos = source.index("// The 18 fields — locked order")
    assert report_header_pos < small_warning_pos < first_field_pos


def test_copy_result_preserves_uncertainty_warning():
    source = _frontend_source()

    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in source
    assert "VERIFY BEFORE RELYING:" in source
    assert "Uncertainty / verification warnings" in source
    assert source.index("VERIFY BEFORE RELYING:") < source.index("Generated by PermitAssist")


def test_dallas_evidence_exposure_limits_are_visible_in_standard_report_and_copy_views():
    source = _frontend_source()

    required = [
        "Evidence-pack exposure limits",
        "Failed-closed evidence fields:",
        "fee_range",
        "inspections",
        "statutory/AHJ outer deadline only — not a local queue or plan-review estimate",
        "not a complete local specialty-trigger list",
        "Exact portal subcategory and filing path still need AHJ/portal verification before filing",
        "Failed-closed evidence fields:",
    ]
    for text in required:
        assert text in source

    standard_warning_pos = source.index("Evidence-pack exposure limits")
    hero_pos = source.index('html += `<div class="result-hero">')
    assert standard_warning_pos < hero_pos

    report_body = _function_body(source, "renderResultAsReport")
    small_warning_pos = report_body.index("PermitAssist is guidance only")
    missing_rollup_pos = report_body.index("failed closed: ${field}")
    assert small_warning_pos < missing_rollup_pos


def test_dallas_evidence_caveats_are_surface_scoped_to_copy_and_report():
    source = _frontend_source()
    copy_body = _function_body(source, "copyResult")
    report_body = _function_body(source, "renderResultAsReport")
    warning_builder_body = _function_body(source, "buildUncertaintyWarnings")

    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in copy_body
    assert "reportUncertaintyWarnings.map" not in report_body
    assert "const reportUncertaintyWarnings = buildUncertaintyWarnings(d);" not in report_body
    assert "buildEvidencePackCaveats(evidencePack)" in warning_builder_body
    assert "buildEvidencePackCaveats(evidencePack)" in warning_builder_body.split("qualityWarnings.slice", 1)[0]
    assert "slice(0, 14)" in warning_builder_body

    shared_builder_body = _function_body(source, "buildEvidencePackCaveats")
    required_surface_caveats = [
        "not a complete local specialty-trigger list",
        "Exact portal subcategory and filing path still need AHJ/portal verification before filing",
    ]

    for caveat in required_surface_caveats:
        assert caveat in shared_builder_body


def test_dallas_evidence_surfaces_use_one_shared_caveat_builder():
    source = _frontend_source()

    assert "function buildEvidencePackCaveats" in source
    assert _function_body(source, "renderResults").count("buildEvidencePackCaveats") >= 1
    assert _function_body(source, "buildUncertaintyWarnings").count("buildEvidencePackCaveats") >= 1
