from pathlib import Path


FRONTEND_INDEX = Path(__file__).resolve().parents[1] / "frontend" / "index.html"


def _frontend_source() -> str:
    return FRONTEND_INDEX.read_text(encoding="utf-8")


def test_standard_result_view_surfaces_uncertainty_above_the_fold():
    source = _frontend_source()

    assert "function buildUncertaintyWarnings" in source
    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in source
    assert "uncertainty-warning-card" in source
    assert "Verify before relying on this result" in source

    hero_pos = source.index('html += `<div class="result-hero">')
    warning_pos = source.index("uncertainty-warning-card")
    assert warning_pos < hero_pos


def test_report_view_uses_same_loud_uncertainty_rollup():
    source = _frontend_source()

    assert "const reportUncertaintyWarnings = buildUncertaintyWarnings(d);" in source
    assert "Report needs verification" in source
    assert "This warning is intentionally shown in report/print view" in source

    report_header_pos = source.index("PermitAssist Report v1.0")
    report_warning_pos = source.index("Report needs verification")
    first_field_pos = source.index("// The 18 fields — locked order")
    assert report_header_pos < report_warning_pos < first_field_pos


def test_copy_result_preserves_uncertainty_warning():
    source = _frontend_source()

    assert "const uncertaintyWarnings = buildUncertaintyWarnings(d);" in source
    assert "VERIFY BEFORE RELYING:" in source
    assert "Uncertainty / verification warnings" in source
    assert source.index("VERIFY BEFORE RELYING:") < source.index("Generated by PermitAssist")
